# Generated by Django 4.2.7 on 2025-06-30 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('is_public', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborated_documents', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_modified'],
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('insert', 'Insert'), ('delete', 'Delete'), ('retain', 'Retain')], max_length=10)),
                ('position', models.PositiveIntegerField()),
                ('content', models.TextField(blank=True)),
                ('length', models.PositiveIntegerField(default=0)),
                ('version', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['document', 'timestamp'], name='documents_o_documen_6b8b79_idx'), models.Index(fields=['document', 'version'], name='documents_o_documen_16c0a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cursor_position', models.JSONField(default=dict)),
                ('selection', models.JSONField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('channel_name', models.CharField(blank=True, max_length=255)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['document', 'is_active'], name='documents_d_documen_7f9cf6_idx'), models.Index(fields=['last_seen'], name='documents_d_last_se_bfeefd_idx')],
                'unique_together': {('document', 'user')},
            },
        ),
        migrations.CreateModel(
            name='DocumentInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='documents.document')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['invited_user', 'is_accepted'], name='documents_d_invited_b435f6_idx')],
                'unique_together': {('document', 'invited_user')},
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_by', '-last_modified'], name='documents_d_created_9e9c12_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_public', '-last_modified'], name='documents_d_is_publ_850406_idx'),
        ),
    ]
